name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Automate approvals
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: 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
          ADD_LABEL: "Good to Go!"
